#!/usr/bin/env python
"""Render the gitleaks email allowlist from the same lists the gate reads.

CONTRIBUTING used to say these two "must stay in step", which is a hand-maintained
invariant -- exactly what this project's rules say to replace with a mechanism. They
drifted within an hour of being written: the gate was fixed and gitleaks was not, and CI
caught it.

    python scripts/gen_gitleaks_config.py           # write
    python scripts/gen_gitleaks_config.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import atexit
import re
import shutil
import sys
import tempfile
from pathlib import Path

sys.pycache_prefix = tempfile.mkdtemp(prefix="cdl-gl-pyc-")
# ...and removed when this process exits; see the note in docs_gate.py for the measurement
# that prompted it.
atexit.register(shutil.rmtree, sys.pycache_prefix, ignore_errors=True)

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / ".gitleaks.toml"
START = "# GEN:EMAILS:START"
END = "# GEN:EMAILS:END"


def read(name: str) -> list[str]:
    p = ROOT / "security" / name
    if not p.exists():
        return []
    return [ln.strip() for ln in p.read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.strip().startswith("#")]


def render() -> str:
    addrs = read("allowed_emails.txt") + read("content_safe_emails.txt")
    lines = [
        START,
        "  # Generated by scripts/gen_gitleaks_config.py from security/allowed_emails.txt",
        "  # and security/content_safe_emails.txt. Do not edit: the gate regenerates this",
        "  # block and fails when it differs. Two scanners, one source of truth.",
    ]
    for a in addrs:
        lines.append(f"  '''{re.escape(a)}''',")
    # RFC 2606 reserved domains, by rule rather than by enumeration -- matching the gate.
    lines.append("  # RFC 2606 reserved domains: these identify nobody by construction.")
    lines.append("  '''[A-Za-z0-9._%+-]+@example[.](com|org|net|edu)''',")
    lines.append(f"  {END}")
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(text):
        return pattern.sub(block.rstrip().removesuffix(END).rstrip() + "\n  " + END, text)
    raise SystemExit(f"{TARGET.name} has no {START} / {END} markers")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    existing = TARGET.read_text(encoding="utf-8")
    updated = splice(existing, render())

    if args.check:
        if existing == updated:
            print(f"ok: {TARGET.name} email allowlist is current")
            return 0
        print(f"STALE: {TARGET.name} does not match the security/ lists. "
              f"Run: python scripts/gen_gitleaks_config.py")
        return 1

    TARGET.write_text(updated, encoding="utf-8")
    print(f"updated: {TARGET.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
